<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>ORDON Organ Donation Completion Certificate</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; background: #f2fbff; color: #0b3650; }
        .wrap { border: 6px double #0b3650; padding: 38px; margin: 15px; background: #ffffff; }
        .title { font-size: 30px; font-weight: bold; text-align: center; margin-bottom: 8px; text-transform: uppercase; letter-spacing: 1px; }
        .subtitle { text-align: center; color: #335b74; margin-bottom: 24px; font-size: 14px; }
        .name { font-size: 32px; font-weight: bold; text-align: center; margin: 14px 0; border-bottom: 1px solid #9ac8e4; display: inline-block; padding: 0 18px 8px; }
        .line { text-align: center; font-size: 16px; margin: 7px 0; }
        .meta { margin-top: 18px; font-size: 14px; text-align: center; }
        .foot { margin-top: 28px; font-size: 12px; color: #5d7d92; text-align: center; }
        .qr { text-align: center; margin-top: 16px; }
        .cert-id { font-size: 13px; text-align: center; margin-top: 8px; }
    </style>
</head>
<body>
    <div class="wrap">
        <div class="title">Certificate of Organ Donation Completion</div>
        <div class="subtitle">Issued by ORDON National Transplant Coordination Platform</div>
        <div class="line">This is to formally certify that</div>
        <p style="text-align:center"><span class="name">{{ $user->name }}</span></p>
        <div class="line">has completed a successful organ donation procedure through ORDON.</div>
        <div class="meta">
            Organ Type: <strong>{{ ucfirst($donor->organ_type) }}</strong><br>
            Blood Group: <strong>{{ $donor->blood_group }}</strong><br>
            Hospital: <strong>{{ $completedTransplant->hospital->name ?? 'N/A' }}</strong><br>
            Recipient: <strong>{{ $completedTransplant->recipient_name_override ?: ($completedTransplant->match->recipient->user->name ?? 'N/A') }}</strong><br>
            Completion Date: <strong>{{ $completedTransplant->updated_at?->format('d M Y') }}</strong>
        </div>
        <div class="cert-id">Certificate ID: <strong>{{ $certificateId }}</strong></div>
        <div class="qr">
            <img src="https://api.qrserver.com/v1/create-qr-code/?size=130x130&data={{ rawurlencode($certificateId) }}" alt="Certificate QR">
        </div>
        <div class="foot">Issued on {{ $issuedAt->format('d M Y, h:i A') }} | Digitally generated by ORDON</div>
    </div>
</body>
</html>
